//! Fleet integration against the exact Grove release: fake shell executors,
//! real worktrees, claims, receipts, and the ranked report. A missing or
//! incompatible Grove is a test failure, never a successful skip.
#![cfg(unix)]

use serde_json::Value;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::thread;
use std::time::{Duration, Instant};
use tempfile::TempDir;

const SUMMONER: &str = env!("CARGO_BIN_EXE_summoner");

fn grove_bin() -> String {
    std::env::var("SUMMONER_TEST_GROVE").unwrap_or_else(|_| "grove".to_string())
}

fn require_grove() {
    let output = Command::new(grove_bin())
        .arg("--version")
        .output()
        .expect("Grove 0.4.0 must be installed or SUMMONER_TEST_GROVE must name it");
    assert!(
        output.status.success(),
        "Grove --version failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8_lossy(&output.stdout).trim(),
        "grove 0.4.0",
        "fleet tests require the exact qualified Grove release"
    );
    let output = Command::new(grove_bin())
        .args(["task", "status", "--json"])
        .output()
        .expect("run Grove task status compatibility probe");
    assert!(output.status.success(), "Grove task status probe failed");
    let status: Value =
        serde_json::from_slice(&output.stdout).expect("Grove task status must be valid JSON");
    assert_eq!(status["schema_version"], 4, "wrong Grove task schema");
}

macro_rules! require_grove {
    () => {
        require_grove();
    };
}

struct Fixture {
    base: TempDir,
    repo: PathBuf,
    with_verification: bool,
}

const GROVE_TOML: &str = r#"[verification]
required = ["fast"]

[verification.profiles.fast]
continue_on_failure = false
commands = [{ argv = ["true"], allow_zero_tests = true }]
"#;

impl Fixture {
    /// A committed cargo package with git identity; verification profile and
    /// summoner config are committed so they predate every scope snapshot.
    fn new(with_verification: bool) -> Fixture {
        let base = TempDir::new().unwrap();
        let repo = base.path().join("repo");
        std::fs::create_dir_all(repo.join("src")).unwrap();
        std::fs::write(
            repo.join("Cargo.toml"),
            "[package]\nname='p'\nversion='0.1.0'\nedition='2021'\n",
        )
        .unwrap();
        std::fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"p\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        std::fs::write(repo.join("src/lib.rs"), "").unwrap();
        if with_verification {
            std::fs::write(repo.join(".grove.toml"), GROVE_TOML).unwrap();
        }
        let fixture = Fixture {
            base,
            repo,
            with_verification,
        };
        fixture.git(&["init", "-q"]);
        fixture.git(&["config", "user.email", "t@example.com"]);
        fixture.git(&["config", "user.name", "fleet-test"]);
        fixture
    }

    fn git(&self, args: &[&str]) {
        let status = Command::new("git")
            .args(args)
            .current_dir(&self.repo)
            .status()
            .expect("run git");
        assert!(status.success(), "git {args:?} failed");
    }

    fn commit_all(&self, message: &str) {
        self.git(&["add", "-A"]);
        self.git(&["commit", "-q", "-m", message]);
    }

    /// One fake executor; the config routes the prompt on stdin, which the
    /// scripts deliberately ignore (prompt composition is unit-tested).
    fn executor(&self, body: &str, timeout_secs: u64) {
        self.executor_raw(
            &format!("{body}\necho '{{\"summoner_status\":\"complete\",\"unmet\":[]}}'"),
            timeout_secs,
        );
    }

    fn executor_raw(&self, body: &str, timeout_secs: u64) {
        let script = self.base.path().join("fake-executor.sh");
        std::fs::write(
            &script,
            format!(
                "#!/bin/sh\nif [ \"${{1-}}\" = --version ]; then echo 'fake-executor 1'; exit 0; fi\n{body}\n"
            ),
        )
        .unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
        // Only point at a default profile the repository actually declares.
        let default_profile = if self.with_verification {
            "default_verify_profile = \"fast\"\n"
        } else {
            ""
        };
        std::fs::write(
            self.repo.join(".summoner.toml"),
            format!(
                "default_executor = \"fake\"\n{default_profile}\
                 max_parallel = 2\n\n[executors.fake]\nargv = [\"{}\"]\nprompt = \"stdin\"\n\
                 timeout_secs = {timeout_secs}\n",
                script.display()
            ),
        )
        .unwrap();
        self.commit_all("fixture");
    }

    /// Extra config lines appended to `.summoner.toml`. Top-level keys must be
    /// appended via this BEFORE `executor()` writes the executor table; lines
    /// appended after land inside `[executors.fake]`, which suits per-executor
    /// keys like `usage_marker`.
    fn append_config(&self, lines: &str) {
        use std::io::Write;
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(self.repo.join(".summoner.toml"))
            .unwrap();
        writeln!(file, "{lines}").unwrap();
        drop(file);
        self.commit_all("config tweak");
    }

    /// A "judge" reviewer backend plus `default_reviewer` pointing at it.
    /// Must run after `executor()`, which rewrites the config file whole.
    fn reviewer(&self, body: &str) {
        let script = self.reviewer_script(body);
        let existing = std::fs::read_to_string(self.repo.join(".summoner.toml")).unwrap();
        std::fs::write(
            self.repo.join(".summoner.toml"),
            format!(
                "default_reviewer = \"judge\"\n{existing}\n[executors.judge]\n\
                 argv = [\"{}\"]\nprompt = \"stdin\"\ntimeout_secs = 60\n",
                script.display()
            ),
        )
        .unwrap();
        self.commit_all("reviewer fixture");
    }

    fn reviewer_script(&self, body: &str) -> PathBuf {
        let script = self.base.path().join("judge-executor.sh");
        std::fs::write(
            &script,
            format!(
                r#"#!/bin/sh
if [ "${{1-}}" = --version ]; then echo 'fake-reviewer 1'; exit 0; fi
prompt=$(cat)
field() {{ printf '%s' "$prompt" | sed -n "s/.*\"$1\":\"\([^\"]*\)\".*/\1/p" | tail -1; }}
legacy=$({body})
verdict=$(printf '%s' "$legacy" | sed -n 's/.*"verdict":"\([^"]*\)".*/\1/p')
findings=${{legacy#*\"findings\":}}
findings=${{findings%\}}}}
printf '{{"protocol_version":1,"review_nonce":"%s","candidate_snapshot_sha256":"%s","diff_sha256":"%s","verdict":"%s","findings":%s,"reviewer":{{"provider":"judge","model":"fake"}}}}\n' \
  "$(field review_nonce)" "$(field candidate_snapshot_sha256)" "$(field diff_sha256)" "$verdict" "$findings"
"#
            ),
        )
        .unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
        script
    }

    fn order(&self, name: &str, body: &str) -> PathBuf {
        let orders = self.base.path().join("orders");
        std::fs::create_dir_all(&orders).unwrap();
        let path = orders.join(name);
        std::fs::write(&path, body).unwrap();
        path
    }

    fn summoner(&self, args: &[&str]) -> Output {
        self.summoner_with_env(args, &[])
    }

    fn summoner_with_env(&self, args: &[&str], envs: &[(&str, &str)]) -> Output {
        let mut command = self.summoner_command(args, &grove_bin());
        for (key, value) in envs {
            command.env(key, value);
        }
        command.output().expect("run summoner")
    }

    fn summoner_command(&self, args: &[&str], grove: &str) -> Command {
        let base = std::fs::canonicalize(self.base.path()).unwrap();
        let mut command = Command::new(SUMMONER);
        command
            .args(args)
            .current_dir(&self.repo)
            .env("SUMMONER_GROVE_BIN", grove)
            .env("GROVE_CACHE_ROOT", base.join("cache"))
            .env("XDG_CONFIG_HOME", base.join("config"))
            .env("XDG_CACHE_HOME", base.join("xdg"));
        // Hermetic against the harness running THIS test suite: profile
        // auto-detection must see only what each test opts into.
        for marker in [
            "CLAUDECODE",
            "CODEX_SANDBOX",
            "CODEX_HOME",
            "SUMMONER_PROFILE",
        ] {
            command.env_remove(marker);
        }
        command
    }

    fn grove(&self, args: &[&str]) -> Output {
        let base = std::fs::canonicalize(self.base.path()).unwrap();
        Command::new(grove_bin())
            .args(args)
            .current_dir(&self.repo)
            .env("GROVE_CACHE_ROOT", base.join("cache"))
            .output()
            .expect("run grove")
    }

    fn run_report(&self, order_paths: &[&Path], expect_exit: i32) -> Value {
        let mut args = vec!["run"];
        args.extend(order_paths.iter().map(|p| p.to_str().unwrap()));
        let output = self.summoner(&args);
        assert_eq!(
            output.status.code(),
            Some(expect_exit),
            "stdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice(&output.stdout).expect("report is JSON")
    }

    fn task_states(&self) -> Vec<(String, String)> {
        let output = self.grove(&["task", "status", "--json"]);
        assert!(output.status.success());
        let report: Value = serde_json::from_slice(&output.stdout).unwrap();
        report["tasks"]
            .as_array()
            .unwrap()
            .iter()
            .map(|task| {
                (
                    task["owner"].as_str().unwrap_or_default().to_string(),
                    task["status"].as_str().unwrap_or_default().to_string(),
                )
            })
            .collect()
    }
}

#[test]
fn clean_rust_example_finishes_with_real_grove_verification() {
    require_grove!();
    let fixture = Fixture::new(false);
    fixture.commit_all("rust workspace");
    let initialized = fixture.summoner(&["init", "--example"]);
    assert!(
        initialized.status.success(),
        "{}",
        String::from_utf8_lossy(&initialized.stderr)
    );
    fixture.executor(
        "mkdir -p docs\nprintf '# Summoner demo\\n\\nThis crate demonstrates a verified Rust fleet.\\n' > docs/summoner-demo.md\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.repo.join("orders/example.toml");
    let report = fixture.run_report(&[&order], 0);
    assert_eq!(report["summary"]["verified"], 1, "{report}");
    assert_eq!(report["orders"][0]["verify"][0]["profile"], "rust-check");
}

const ORDER_TOML: &str = r#"
id = "wave"
title = "Add the wave function"
brief = "Append a function to src/lib.rs and commit."
scope = ["src"]
acceptance = ["src/lib.rs gains a function", "work is committed"]
verify_profile = "fast"
"#;

#[test]
fn happy_path_order_is_verified_released_and_salvaged_to_its_branch() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 0);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "verified", "{report}");
    assert_eq!(entry["executor_exit"], 0);
    assert_eq!(entry["commits"], 1);
    assert_eq!(entry["finish"]["verified"], true);
    assert_eq!(report["summary"]["verified"], 1);

    // The reviewed candidate is identified by an immutable commit captured
    // before release, not just by a branch name that release can advance.
    let candidate = entry["candidate_commit"]
        .as_str()
        .expect("candidate commit recorded before release");
    assert_eq!(
        candidate.len(),
        40,
        "expected a full object id: {candidate}"
    );
    assert_ne!(candidate, entry["base_commit"].as_str().unwrap());
    let reachable = Command::new("git")
        .args(["cat-file", "-e", &format!("{candidate}^{{commit}}")])
        .current_dir(&fixture.repo)
        .status()
        .unwrap();
    assert!(
        reachable.success(),
        "candidate commit {candidate} must survive worktree release"
    );

    // The worktree is gone; the work survives on the order's branch.
    let worktree = entry["worktree"].as_str().unwrap();
    assert!(!Path::new(worktree).exists(), "worktree released");
    let show = Command::new("git")
        .args(["show", "grove/smn-wave:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    assert!(String::from_utf8_lossy(&show.stdout).contains("pub fn wave()"));

    // No claim leaked: the task is terminal.
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "finished".into())]
    );

    // The run left its mark on the cross-run scorecard, and the aggregation
    // command reads it back per repo and executor.
    let output = fixture.summoner(&["scorecard"]);
    assert_eq!(output.status.code(), Some(0));
    let board: Value = serde_json::from_slice(&output.stdout).unwrap();
    let repo_key = board
        .as_object()
        .unwrap()
        .keys()
        .find(|key| key.contains("repo"))
        .expect("repo entry")
        .clone();
    let stats = &board[&repo_key]["fake"];
    assert_eq!(stats["orders"], 1, "{board}");
    assert_eq!(stats["green"], 1, "{board}");
    assert_eq!(stats["outcomes"]["verified"], 1, "{board}");
}

#[test]
fn clean_executor_exit_without_changes_is_not_verified() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("true", 60);
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "unverified", "{report}");
    assert_eq!(entry["executor_exit"], 0);
    assert_eq!(entry["commits"], 0);
    assert_eq!(entry["diff"]["files_changed"], 0);
    assert!(
        entry["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("no changes")),
        "{report}"
    );
    assert!(entry.get("verify").is_none(), "{report}");
}

#[test]
fn executor_declaring_unmet_acceptance_is_not_verified() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor_raw(
        "echo 'pub fn wave() {}' >> src/lib.rs\n\
         git add -A\ngit commit -qm 'partial executor work'\n\
         echo '{\"summoner_status\":\"incomplete\",\"unmet\":[\"wire regression missing\"]}'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "unverified", "{report}");
    assert!(
        entry["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("wire regression missing")),
        "{report}"
    );
    assert!(entry.get("verify").is_none(), "{report}");
}

#[test]
fn verifier_created_ignored_artifacts_do_not_block_release() {
    require_grove!();
    let fixture = Fixture::new(true);
    std::fs::write(fixture.repo.join(".gitignore"), "verify.out\n").unwrap();
    std::fs::write(
        fixture.repo.join(".grove.toml"),
        GROVE_TOML.replace("[\"true\"]", "[\"sh\", \"-c\", \"touch verify.out\"]"),
    )
    .unwrap();
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 0);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "verified", "{report}");
    assert!(!Path::new(entry["worktree"].as_str().unwrap()).exists());
}

#[test]
fn executor_created_ignored_artifacts_remain_protected() {
    require_grove!();
    let fixture = Fixture::new(true);
    std::fs::write(fixture.repo.join(".gitignore"), "executor.out\n").unwrap();
    fixture.executor(
        "echo private > executor.out\n\
         echo 'pub fn wave() {}' >> src/lib.rs\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "error", "{report}");
    assert!(
        entry["release_error"]
            .as_str()
            .is_some_and(|error| error.contains("ignored path")),
        "{report}"
    );
    let worktree = Path::new(entry["worktree"].as_str().unwrap());
    assert_eq!(
        std::fs::read_to_string(worktree.join("executor.out")).unwrap(),
        "private\n"
    );
}

#[test]
fn internal_error_after_commit_preserves_report_evidence() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let wrapper = fixture.base.path().join("failing-grove.sh");
    std::fs::write(
        &wrapper,
        format!(
            "#!/bin/sh\n\
             if [ \"$1\" = verify ]; then echo 'forced verify failure' >&2; exit 2; fi\n\
             exec '{}' \"$@\"\n",
            grove_bin().replace('\'', "'\\''")
        ),
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
    let order = fixture.order("wave.toml", ORDER_TOML);

    let output = fixture.summoner_with_env(
        &["run", order.to_str().unwrap()],
        &[("SUMMONER_GROVE_BIN", wrapper.to_str().unwrap())],
    );
    assert_eq!(output.status.code(), Some(1));
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "error", "{report}");
    assert_eq!(entry["commits"], 1, "{report}");
    assert_eq!(entry["diff"]["files_changed"], 1, "{report}");
    assert!(
        entry["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("forced verify failure")),
        "{report}"
    );
}

#[test]
fn approving_reviewer_upgrades_verified_to_approved_and_exit_zero() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    fixture.reviewer("echo '{\"verdict\":\"approve\",\"findings\":[]}'");
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 0);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "approved", "{report}");
    assert_eq!(entry["review"]["reviewer"], "judge", "{report}");
    assert_eq!(entry["review"]["verdict"], "approve", "{report}");
    let snapshot = entry["review"]["candidate_snapshot_sha256"]
        .as_str()
        .expect("report carries the reviewed snapshot digest");
    assert_eq!(snapshot.len(), 64, "{report}");
    assert!(entry["review"].get("candidate_source_sha256").is_none());
    assert!(entry["review"].get("candidate_tree").is_none());
    assert_eq!(entry["finish"]["verified"], true, "{report}");
    assert_eq!(report["summary"]["approved"], 1, "{report}");
    // The review prompt is on disk next to the executor's: independent record.
    let prompt = std::fs::read_to_string(
        PathBuf::from(entry["review"]["stdout_log"].as_str().unwrap())
            .parent()
            .unwrap()
            .join("review-prompt.md"),
    )
    .unwrap();
    assert!(
        prompt.contains("# Review charter"),
        "review charter present"
    );
    assert!(
        !prompt.contains("# Worker charter"),
        "implementer charter must not leak into the review"
    );
    // The gate is observable live: review_started names the logs to tail
    // before any verdict exists, and the verdict event follows it.
    let events_path = fixture
        .base
        .path()
        .join("xdg/summoner/runs")
        .join(report["run_id"].as_str().unwrap())
        .join("events.jsonl");
    let events = std::fs::read_to_string(&events_path).unwrap();
    let started_at = events.find("\"review_started\"").expect("review_started");
    let verdict_at = events.find("\"order_review\"").expect("order_review");
    assert!(started_at < verdict_at, "{events}");
    assert!(events.contains("review-stdout.log"), "{events}");
    let review_events = events
        .lines()
        .filter_map(|line| serde_json::from_str::<Value>(line).ok())
        .filter(|event| {
            matches!(
                event["event"].as_str(),
                Some("review_started" | "order_review")
            )
        })
        .collect::<Vec<_>>();
    assert_eq!(review_events.len(), 2, "{events}");
    for event in review_events {
        assert_eq!(event["candidate_snapshot_sha256"], snapshot, "{event}");
        assert_eq!(event["diff_sha256"], entry["review"]["diff_sha256"]);
        assert!(event.get("source_sha256").is_none(), "{event}");
        assert!(event.get("candidate_tree").is_none(), "{event}");
    }
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "finished".into())]
    );
}

#[test]
fn orchestrator_profile_switches_the_reviewer_on_by_harness_marker() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    // The judge exists but is wired only through the claude profile: which
    // orchestrator invokes summoner decides whether the gate is on.
    let script = fixture.reviewer_script("echo '{\"verdict\":\"approve\",\"findings\":[]}'");
    let existing = std::fs::read_to_string(fixture.repo.join(".summoner.toml")).unwrap();
    std::fs::write(
        fixture.repo.join(".summoner.toml"),
        format!(
            "{existing}\n[executors.judge]\nargv = [\"{}\"]\nprompt = \"stdin\"\n\
             timeout_secs = 60\n\n[profiles.claude]\ndefault_reviewer = \"judge\"\n",
            script.display()
        ),
    )
    .unwrap();
    fixture.commit_all("profile fixture");
    let order = fixture.order("wave.toml", ORDER_TOML);

    // Bare invocation: no marker, no profile, no gate.
    let output = fixture.summoner(&["run", order.to_str().unwrap()]);
    assert_eq!(output.status.code(), Some(0));
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["orders"][0]["outcome"], "verified", "{report}");

    // The same command from a Claude Code shell auto-selects [profiles.claude].
    let output =
        fixture.summoner_with_env(&["run", order.to_str().unwrap()], &[("CLAUDECODE", "1")]);
    assert_eq!(
        output.status.code(),
        Some(0),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["orders"][0]["outcome"], "approved", "{report}");
    assert_eq!(
        report["orders"][0]["review"]["reviewer"], "judge",
        "{report}"
    );
}

#[test]
fn rejected_work_is_revised_with_findings_in_a_resumed_session() {
    require_grove!();
    let fixture = Fixture::new(true);
    // Attempt 1: prints a session banner, commits work the judge will reject.
    fixture.executor(
        "echo 'session id: sess-42'\n\
         echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm w",
        60,
    );
    // The revision resumes the session: a different script that receives
    // {session_id}, records it, and fixes the work.
    let resume = fixture.base.path().join("resume-executor.sh");
    std::fs::write(
        &resume,
        format!(
            "#!/bin/sh\necho \"$1\" > {}\ncat > {}\n\
             echo 'pub fn fixed() {{}}' >> src/lib.rs\ngit add -A\ngit commit -qm fix\n\
             echo '{{\"summoner_status\":\"complete\",\"unmet\":[]}}'\n",
            fixture.base.path().join("resumed-with.txt").display(),
            fixture.base.path().join("revision-prompt.txt").display(),
        ),
    )
    .unwrap();
    std::fs::set_permissions(&resume, std::fs::Permissions::from_mode(0o755)).unwrap();
    fixture.append_config(&format!(
        "session_marker = \"session id:\"\nresume_argv = [\"{}\", \"{{session_id}}\"]",
        resume.display()
    ));
    // The judge rejects the first attempt and approves the second.
    let flag = fixture.base.path().join("judged-once");
    fixture.reviewer(&format!(
        "if [ -f {flag} ]; then echo '{{\"verdict\":\"approve\",\"findings\":[]}}'; \
         else touch {flag}; \
         echo '{{\"verdict\":\"reject\",\"findings\":[{{\"severity\":\"blocker\",\"file\":\"src/lib.rs\",\"line\":1,\"summary\":\"wave is wrong\"}}]}}'; fi",
        flag = flag.display()
    ));
    let order = fixture.order("wave.toml", ORDER_TOML);

    let output = fixture.summoner_with_env(
        &["run", order.to_str().unwrap()],
        &[("SUMMONER_REVISE", "1")],
    );
    assert_eq!(
        output.status.code(),
        Some(0),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "approved", "{report}");
    assert_eq!(entry["attempts"], 2, "{report}");
    assert_eq!(entry["session_id"], "sess-42", "{report}");
    assert_eq!(entry["review"]["verdict"], "approve", "{report}");

    // The resume template really received the captured session id...
    let resumed = std::fs::read_to_string(fixture.base.path().join("resumed-with.txt")).unwrap();
    assert_eq!(resumed.trim(), "sess-42");
    // ...and the revision prompt carried the findings, not the full charter
    // (the session already has it).
    let prompt = std::fs::read_to_string(fixture.base.path().join("revision-prompt.txt")).unwrap();
    assert!(prompt.contains("wave is wrong"), "{prompt}");
    assert!(!prompt.contains("# Worker charter"), "{prompt}");

    // Both attempts' work landed on the branch.
    let show = Command::new("git")
        .args(["show", "grove/smn-wave:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    let lib = String::from_utf8_lossy(&show.stdout).into_owned();
    assert!(lib.contains("pub fn wave()"), "{lib}");
    assert!(lib.contains("pub fn fixed()"), "{lib}");
}

#[test]
fn run_token_budget_skips_the_rest_of_the_queue() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn f() {}' >> src/lib.rs\ngit add -A\ngit commit -qm w\necho 'tokens used'\necho 500",
        60,
    );
    fixture.append_config("usage_marker = \"tokens used\"");
    let a = fixture.order(
        "a.toml",
        "id = \"a\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src\"]\nverify_profile = \"fast\"\n",
    );
    let b = fixture.order(
        "b.toml",
        "id = \"b\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"docs\"]\nverify_profile = \"fast\"\n",
    );

    let output = fixture.summoner_with_env(
        &["run", a.to_str().unwrap(), b.to_str().unwrap()],
        &[
            ("SUMMONER_MAX_PARALLEL", "1"),
            ("SUMMONER_RUN_TOKEN_BUDGET", "100"),
        ],
    );
    assert_eq!(output.status.code(), Some(1));
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["summary"]["verified"], 1, "{report}");
    assert_eq!(report["summary"]["skipped"], 1, "{report}");
    let skipped = report["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|entry| entry["outcome"] == "skipped")
        .unwrap();
    assert!(
        skipped["detail"]
            .as_str()
            .unwrap()
            .contains("budget exhausted"),
        "{report}"
    );
}

#[test]
fn rejecting_reviewer_downgrades_verified_work_and_carries_findings() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    fixture.reviewer(
        "echo '{\"verdict\":\"reject\",\"findings\":[{\"severity\":\"blocker\",\"file\":\"src/lib.rs\",\"line\":1,\"summary\":\"hardcoded expected value\"}]}'",
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "rejected", "{report}");
    assert_eq!(
        entry["review"]["findings"][0]["summary"], "hardcoded expected value",
        "{report}"
    );
    // The work is still finished and salvaged: the orchestrator reviews the
    // findings against a real branch, not a lost worktree.
    assert_eq!(entry["finish"]["verified"], true, "{report}");
    let show = Command::new("git")
        .args(["show", "grove/smn-wave:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    assert!(String::from_utf8_lossy(&show.stdout).contains("pub fn wave()"));
}

#[test]
fn a_reviewer_that_mutates_its_capsule_voids_the_verdict_and_source_stays_exact() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    // The worst reviewer: plants an untracked file AND stages a malicious
    // edit to an in-scope file before approving its own tampering.
    fixture.reviewer(
        "chmod u+w . src src/lib.rs\n\
         echo sneaky > planted.txt\n\
         echo 'pub fn sneak() {}' >> src/lib.rs\ngit add src/lib.rs\n\
         echo '{\"verdict\":\"approve\",\"findings\":[]}'",
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "review_failed", "{report}");
    assert!(
        entry["review"]["detail"]
            .as_str()
            .unwrap()
            .contains("did not authorize"),
        "{report}"
    );
    // Neither write reaches the branch; the executor's work does.
    let show = Command::new("git")
        .args(["show", "grove/smn-wave:planted.txt"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    assert!(!show.status.success(), "planted file must not be salvaged");
    let show = Command::new("git")
        .args(["show", "grove/smn-wave:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    let lib = String::from_utf8_lossy(&show.stdout).into_owned();
    assert!(lib.contains("pub fn wave()"), "{lib}");
    assert!(!lib.contains("sneak"), "staged edit must be undone: {lib}");
}

#[test]
fn finish_cas_rejects_a_candidate_mutated_and_reverted_during_finish() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    fixture.reviewer("echo '{\"verdict\":\"approve\",\"findings\":[]}'");
    let order = fixture.order("wave.toml", ORDER_TOML);
    let wrapper = fixture.base.path().join("grove-finish-race.sh");
    std::fs::write(
        &wrapper,
        r#"#!/bin/sh
case " $* " in
  *" --expected-source-sha256 "*)
    cp src/lib.rs "$MUTATE_SAVE"
    echo 'pub fn raced() {}' >> src/lib.rs
    "$REAL_GROVE" "$@" > "$WRAP_OUT" 2> "$WRAP_ERR"
    code=$?
    cp "$MUTATE_SAVE" src/lib.rs
    cat "$WRAP_OUT"
    cat "$WRAP_ERR" >&2
    exit "$code" ;;
  *) exec "$REAL_GROVE" "$@" ;;
esac
"#,
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
    let output = fixture
        .summoner_command(&["run", order.to_str().unwrap()], wrapper.to_str().unwrap())
        .env("REAL_GROVE", grove_bin())
        .env("MUTATE_SAVE", fixture.base.path().join("source.saved"))
        .env("WRAP_OUT", fixture.base.path().join("finish.stdout"))
        .env("WRAP_ERR", fixture.base.path().join("finish.stderr"))
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(1));
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["orders"][0]["outcome"], "unverified", "{report}");
    assert!(
        report["orders"][0]["detail"]
            .as_str()
            .unwrap()
            .contains("changed after review"),
        "{report}"
    );
    let saved = Command::new("git")
        .args(["show", "grove/smn-wave:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    let saved = String::from_utf8_lossy(&saved.stdout);
    assert!(saved.contains("wave"), "{saved}");
    assert!(!saved.contains("raced"), "{saved}");
}

#[test]
fn modifying_verification_config_caps_the_outcome_at_unverified() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo '# weakened' >> .grove.toml\ngit add -A\ngit commit -qm 'hack the verifier'",
        60,
    );
    let order = fixture.order(
        "hack.toml",
        r#"
id = "hack"
title = "Try to weaken the gate"
brief = "Modify the verification config."
scope = ["src", ".grove.toml"]
verify_profile = "fast"
"#,
    );

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "unverified", "{report}");
    assert!(
        entry["detail"].as_str().unwrap().contains("protected"),
        "{report}"
    );
    assert_eq!(
        entry["tripwires"][0], "protected file modified: .grove.toml",
        "{report}"
    );
    // Nothing was verified or finished on a compromised config.
    assert_eq!(
        fixture.task_states(),
        [("smn-hack".into(), "abandoned".into())]
    );
}

#[test]
fn variants_race_the_same_scope_and_both_land_on_their_own_branches() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn from_fake() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'fake work'",
        60,
    );
    // A second backend racing the same order: same scope, different output.
    let script = fixture.base.path().join("fake2-executor.sh");
    std::fs::write(
        &script,
        "#!/bin/sh\necho 'pub fn from_fake2() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'fake2 work'\n",
    )
    .unwrap();
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
    fixture.append_config(&format!(
        "\n[executors.fake2]\nargv = [\"{}\"]\nprompt = \"stdin\"\ntimeout_secs = 60",
        script.display()
    ));
    let order = fixture.order(
        "race.toml",
        r#"
id = "race"
title = "Race two executors over one order"
brief = "Append a function to src/lib.rs and commit."
scope = ["src"]
verify_profile = "fast"
variants = ["fake", "fake2"]
"#,
    );

    let report = fixture.run_report(&[&order], 0);
    assert_eq!(report["summary"]["verified"], 2, "{report}");
    for (entry, executor) in report["orders"]
        .as_array()
        .unwrap()
        .iter()
        .zip(["fake", "fake2"])
    {
        assert_eq!(entry["id"], format!("race-{executor}"), "{report}");
        assert_eq!(entry["outcome"], "verified", "{report}");
        assert_eq!(entry["executor"], executor, "{report}");
        assert_eq!(entry["variant_of"], "race", "{report}");
        assert_eq!(
            entry["branch"],
            format!("grove/smn-race-{executor}"),
            "{report}"
        );
    }

    // Each attempt survives on its own branch; the orchestrator lands a winner.
    for (executor, marker) in [("fake", "from_fake()"), ("fake2", "from_fake2()")] {
        let show = Command::new("git")
            .args(["show", &format!("grove/smn-race-{executor}:src/lib.rs")])
            .current_dir(&fixture.repo)
            .output()
            .unwrap();
        assert!(
            String::from_utf8_lossy(&show.stdout).contains(marker),
            "branch for {executor} missing {marker}"
        );
    }

    let mut states = fixture.task_states();
    states.sort();
    assert_eq!(
        states,
        [
            ("smn-race-fake".into(), "finished".into()),
            ("smn-race-fake2".into(), "finished".into()),
        ]
    );
}

#[test]
fn conflicting_scope_reports_blocked_without_dispatching() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("exit 0", 60);
    let order = fixture.order("wave.toml", ORDER_TOML);

    let held = fixture.grove(&["claim", "--agent", "blocker", "--task", "hold", "src"]);
    assert!(
        held.status.success(),
        "{}",
        String::from_utf8_lossy(&held.stderr)
    );

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "blocked", "{report}");
    assert!(entry["conflicts"].as_array().is_some_and(|c| !c.is_empty()));
    assert!(entry["task_id"].is_null(), "no task was begun");
}

#[test]
fn sleeping_executor_is_stalled_by_the_grove_deadline_and_abandoned() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("sleep 30", 2);
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "stalled", "{report}");
    assert_eq!(entry["executor_exit"], 124);
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "abandoned".into())]
    );
}

#[test]
fn failing_executor_skips_verification_and_is_abandoned() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("exit 3", 60);
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "executor_failed", "{report}");
    assert_eq!(entry["executor_exit"], 3);
    assert!(entry.get("verify").is_none(), "verification skipped");
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "abandoned".into())]
    );
}

#[test]
fn out_of_scope_write_is_a_scope_violation() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\necho outside > outside.txt\n\
         git add -A\ngit commit -qm 'overreach'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "scope_violation", "{report}");
    assert!(
        entry["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("outside.txt")),
        "{report}"
    );
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "abandoned".into())]
    );
}

#[test]
fn repo_without_required_profiles_completes_with_the_override_recorded() {
    require_grove!();
    let fixture = Fixture::new(false);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order(
        "wave.toml",
        r#"
id = "wave"
title = "Add the wave function"
brief = "Append a function to src/lib.rs and commit."
scope = ["src"]
"#,
    );

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "completed", "{report}");
    assert!(
        entry["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("no required verification profiles"))
    );
    assert_eq!(
        fixture.task_states(),
        [("smn-wave".into(), "finished".into())]
    );
}

#[test]
fn plan_refutes_a_batch_then_passes_it_once_revised() {
    require_grove!();
    // A real two-crate workspace: app depends on core.
    let base = TempDir::new().unwrap();
    let repo = base.path().join("ws");
    for (name, extra) in [("core", ""), ("app", "core = { path = \"../core\" }\n")] {
        let dir = repo.join("crates").join(name);
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(
            dir.join("Cargo.toml"),
            format!(
                "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n{extra}"
            ),
        )
        .unwrap();
        std::fs::write(dir.join("src/lib.rs"), "").unwrap();
    }
    std::fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/core\", \"crates/app\"]\nresolver = \"2\"\n",
    )
    .unwrap();
    std::fs::write(
        repo.join(".summoner.toml"),
        "default_executor = \"fake\"\n\
         [executors.fake]\nargv = [\"true\"]\nprompt = \"stdin\"\ntimeout_secs = 60\n\
         [executors.fake2]\nargv = [\"true\"]\nprompt = \"stdin\"\ntimeout_secs = 60\n",
    )
    .unwrap();
    let git = |args: &[&str]| {
        assert!(
            Command::new("git")
                .args(args)
                .current_dir(&repo)
                .output()
                .unwrap()
                .status
                .success()
        );
    };
    git(&["init", "-q"]);
    git(&["config", "user.email", "t@e.com"]);
    git(&["config", "user.name", "t"]);
    git(&["add", "-A"]);
    git(&["commit", "-qm", "init"]);

    let orders = base.path().join("orders");
    std::fs::create_dir_all(&orders).unwrap();
    std::fs::write(
        orders.join("core.toml"),
        "id = \"core-work\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"crate:core\"]\n",
    )
    .unwrap();
    std::fs::write(
        orders.join("app.toml"),
        "id = \"app-work\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"crate:app\"]\n",
    )
    .unwrap();

    let plan = |expect_exit: i32| -> Value {
        let output = Command::new(SUMMONER)
            .args(["plan", orders.to_str().unwrap()])
            .current_dir(&repo)
            .env("SUMMONER_GROVE_BIN", grove_bin())
            .env("GROVE_CACHE_ROOT", base.path().join("cache"))
            .output()
            .unwrap();
        assert_eq!(
            output.status.code(),
            Some(expect_exit),
            "stdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice(&output.stdout).unwrap()
    };

    // Package topology is useful context, but disjoint work orders may run in
    // parallel even when one package depends on the other.
    let report = plan(0);
    assert_eq!(report["verdict"], "clean", "{report}");
    assert!(report["missing_after"].is_null(), "{report}");
    assert_eq!(
        report["partition"]["couplings"][0]["kind"], "dependency",
        "{report}"
    );

    // Declare the suggested edge: clean, with a two-wave schedule.
    std::fs::write(
        orders.join("app.toml"),
        "id = \"app-work\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"crate:app\"]\nafter = [\"core-work\"]\n",
    )
    .unwrap();
    let report = plan(0);
    assert_eq!(report["verdict"], "clean", "{report}");
    assert_eq!(
        report["partition"]["waves"],
        serde_json::json!([["core-work"], ["app-work"]])
    );

    // A genuine claim conflict needs ordering.
    std::fs::write(
        orders.join("clash.toml"),
        "id = \"clash\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"crates/core/src\"]\n",
    )
    .unwrap();
    let report = plan(1);
    assert_eq!(report["verdict"], "revise", "{report}");
    assert!(
        report["partition"]["conflicts"]
            .as_array()
            .is_some_and(|c| !c.is_empty()),
        "{report}"
    );

    // Once explicitly serialized, the overlap is dispatchable.
    std::fs::write(
        orders.join("clash.toml"),
        "id = \"clash\"\ntitle = \"t\"\nbrief = \"b\"\n\
         scope = [\"crates/core/src\"]\nafter = [\"core-work\"]\n",
    )
    .unwrap();
    let report = plan(0);
    assert_eq!(report["verdict"], "clean", "{report}");

    // Variant siblings deliberately share scope; their claim group flows
    // through the partition, so an N-version race plans clean.
    std::fs::write(
        orders.join("race.toml"),
        "id = \"race\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"README.md\"]\n\
         variants = [\"fake\", \"fake2\"]\n",
    )
    .unwrap();
    let report = plan(0);
    assert_eq!(report["verdict"], "clean", "{report}");
    // The ordered clash conflict remains listed; the point is the siblings'
    // deliberate overlap never registers as one.
    for conflict in report["partition"]["conflicts"].as_array().unwrap() {
        for side in ["a", "b"] {
            assert!(
                !conflict[side]
                    .as_str()
                    .is_some_and(|id| id.starts_with("race-")),
                "{report}"
            );
        }
    }
}

#[test]
fn sigterm_tears_down_the_fleet_and_still_emits_a_partial_report() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("sleep 30", 60);
    let order = fixture.order(
        "slow.toml",
        "id = \"slow\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/slow.rs\"]\nverify_profile = \"fast\"\n",
    );

    let stdout_path = fixture.base.path().join("stream.ndjson");
    let mut summoner = Command::new(SUMMONER)
        .args(["run", "--stream", order.to_str().unwrap()])
        .current_dir(&fixture.repo)
        .env("SUMMONER_GROVE_BIN", grove_bin())
        .env("GROVE_CACHE_ROOT", fixture.base.path().join("cache"))
        .env("XDG_CACHE_HOME", fixture.base.path().join("xdg"))
        .stdout(std::fs::File::create(&stdout_path).unwrap())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();

    // Interrupt only once the executor is actually running. A cold worktree
    // acquire is ~10s and stretches further under a loaded CI runner, so the
    // deadline covers that with margin rather than flaking on dispatch timing.
    let deadline = Instant::now() + Duration::from_secs(60);
    loop {
        let streamed = std::fs::read_to_string(&stdout_path).unwrap_or_default();
        if streamed.contains("order_dispatched") {
            break;
        }
        assert!(Instant::now() < deadline, "order never dispatched");
        thread::sleep(Duration::from_millis(100));
    }
    assert!(
        Command::new("kill")
            .args(["-TERM", &summoner.id().to_string()])
            .status()
            .unwrap()
            .success()
    );
    let exit = summoner.wait().unwrap();
    assert_eq!(exit.code(), Some(1), "interrupted run needs review");

    // The stream still ends with a complete report classifying the interrupt.
    let streamed = std::fs::read_to_string(&stdout_path).unwrap();
    let last: Value = serde_json::from_str(streamed.lines().last().unwrap()).unwrap();
    assert_eq!(last["event"], "report", "{streamed}");
    let entry = &last["report"]["orders"][0];
    assert_eq!(entry["outcome"], "interrupted", "{streamed}");

    // No leaked claim, and the worktree came back.
    assert_eq!(
        fixture.task_states(),
        [("smn-slow".into(), "abandoned".into())]
    );
    let worktree = entry["worktree"].as_str().unwrap();
    assert!(!Path::new(worktree).exists(), "worktree released");
}

#[test]
fn fail_fast_skips_the_remaining_queue_after_the_threshold() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor("exit 3", 60);
    // One worker, so exactly one failure lands before the breaker decides
    // about the rest of the queue.
    let config = std::fs::read_to_string(fixture.repo.join(".summoner.toml"))
        .unwrap()
        .replace("max_parallel = 2", "max_parallel = 1");
    std::fs::write(
        fixture.repo.join(".summoner.toml"),
        format!("fail_fast = 1\n{config}"),
    )
    .unwrap();
    fixture.commit_all("fail fast config");

    let a = fixture.order(
        "a.toml",
        "id = \"one\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/one.rs\"]\n",
    );
    let b = fixture.order(
        "b.toml",
        "id = \"two\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/two.rs\"]\n",
    );
    let c = fixture.order(
        "c.toml",
        "id = \"zzz\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/three.rs\"]\n",
    );

    let report = fixture.run_report(&[&a, &b, &c], 1);
    assert_eq!(report["summary"]["executor_failed"], 1, "{report}");
    assert_eq!(report["summary"]["skipped"], 2, "{report}");
    let skipped = report["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["outcome"] == "skipped")
        .unwrap();
    assert!(
        skipped["detail"]
            .as_str()
            .is_some_and(|d| d.contains("fail_fast")),
        "{report}"
    );
}

#[test]
fn usage_marker_records_tokens_per_order_and_per_run() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm work\n\
         echo 'tokens used'\necho '1,234'",
        60,
    );
    fixture.append_config("usage_marker = \"tokens used\"");
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 0);
    assert_eq!(report["orders"][0]["usage_tokens"], 1234, "{report}");
    assert_eq!(report["usage_tokens"], 1234, "{report}");
}

/// A configured usage_marker that never matches the executor's output must
/// surface as a tripwire on the report — including the successful verified
/// path, where a prior version had the diff scan overwrite the warning. A
/// silent hole in budget accounting is exactly what this warning exists to
/// prevent.
#[test]
fn an_unmatched_usage_marker_warns_on_the_verified_path() {
    require_grove!();
    let fixture = Fixture::new(true);
    // The executor commits real work (so the order verifies) but never prints
    // the configured marker, so token usage cannot be scraped.
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm work",
        60,
    );
    fixture.append_config("usage_marker = \"tokens used\"");
    let order = fixture.order("wave.toml", ORDER_TOML);

    let report = fixture.run_report(&[&order], 0);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "verified", "{report}");
    assert!(
        entry["usage_tokens"].is_null(),
        "nothing was scraped: {entry}"
    );
    let tripwires = entry["tripwires"].as_array().expect("tripwires present");
    assert!(
        tripwires
            .iter()
            .any(|t| t.as_str().unwrap_or_default().contains("usage_marker")
                && t.as_str().unwrap_or_default().contains("never matched")),
        "the unmatched-marker warning must survive to the report: {entry}"
    );
}

#[test]
fn resume_deduplicates_variant_siblings_sharing_one_order_file() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn f() {}' >> src/lib.rs\ngit add -A\ngit commit -qm w",
        60,
    );
    let script = fixture.base.path().join("fake2-executor.sh");
    std::fs::write(
        &script,
        "#!/bin/sh\necho 'pub fn g() {}' >> src/lib.rs\ngit add -A\ngit commit -qm w2\n",
    )
    .unwrap();
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
    fixture.append_config(&format!(
        "\n[executors.fake2]\nargv = [\"{}\"]\nprompt = \"stdin\"\ntimeout_secs = 60",
        script.display()
    ));
    let order = fixture.order(
        "race.toml",
        r#"
id = "race"
title = "t"
brief = "b"
scope = ["src"]
verify_profile = "fast"
variants = ["fake", "fake2"]
"#,
    );

    let report = fixture.run_report(&[&order], 0);
    let run_id = report["run_id"].as_str().unwrap();

    // Both siblings report the same order file; resume must not load it
    // twice (duplicate expanded ids would abort validation).
    let output = fixture.summoner(&["resume", run_id]);
    assert_eq!(
        output.status.code(),
        Some(0),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let resumed: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(resumed["summary"]["verified"], 2, "{resumed}");
    for entry in resumed["orders"].as_array().unwrap() {
        assert!(
            entry["detail"]
                .as_str()
                .is_some_and(|d| d.contains("carried")),
            "{resumed}"
        );
    }
}

#[test]
fn resume_carries_successes_and_reruns_failures_on_their_branches() {
    require_grove!();
    let fixture = Fixture::new(true);
    // Order "bad" fails until the flag file exists; "good" always succeeds.
    let flag = fixture.base.path().join("fixed");
    fixture.executor(
        &format!(
            "branch=$(git symbolic-ref --short HEAD)\n\
             case \"$branch\" in\n\
               *smn-bad) if [ ! -f {flag} ]; then echo 'SESSION=bad-session'; exit 3; fi\n\
                         test \"$1\" = --resume && test \"$2\" = bad-session || exit 4\n\
                         echo 'pub fn bad() {{}}' > src/bad.rs ;;\n\
               *) echo 'pub fn good() {{}}' > src/good.rs ;;\n\
             esac\n\
             git add -A\ngit commit -qm 'executor work'",
            flag = flag.display()
        ),
        60,
    );
    fixture.append_config(&format!(
        "session_marker = \"SESSION=\"\nresume_argv = [\"{}\", \"--resume\", \"{{session_id}}\"]",
        fixture.base.path().join("fake-executor.sh").display()
    ));
    let a = fixture.order(
        "a.toml",
        "id = \"good\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/good.rs\"]\nverify_profile = \"fast\"\n",
    );
    let b = fixture.order(
        "b.toml",
        "id = \"bad\"\ntitle = \"t\"\nbrief = \"b\"\nscope = [\"src/bad.rs\"]\nverify_profile = \"fast\"\n",
    );

    let first = fixture.run_report(&[&a, &b], 1);
    assert_eq!(first["summary"]["verified"], 1, "{first}");
    assert_eq!(first["summary"]["executor_failed"], 1, "{first}");
    let run_id = first["run_id"].as_str().unwrap();

    std::fs::write(&flag, "").unwrap();
    // Recovery owns its inputs: remove both source orders and replace the
    // current executor/defaults with a backend that would fail if consulted.
    std::fs::remove_file(&a).unwrap();
    std::fs::remove_file(&b).unwrap();
    std::fs::write(
        fixture.repo.join(".summoner.toml"),
        "default_executor = \"poison\"\nmax_parallel = 9\n\n\
         [executors.poison]\nargv = [\"false\"]\nprompt = \"stdin\"\n",
    )
    .unwrap();
    fixture.commit_all("replace current summoner config");
    let output = fixture.summoner_with_env(
        &["resume", run_id],
        &[("SUMMONER_MAX_PARALLEL", "7"), ("SUMMONER_REVISE", "4")],
    );
    assert_eq!(
        output.status.code(),
        Some(0),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let second: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(second["summary"]["verified"], 2, "{second}");
    let good = second["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["id"] == "good")
        .unwrap();
    assert!(
        good["detail"]
            .as_str()
            .is_some_and(|d| d.contains("carried from run")),
        "{second}"
    );
    let bad = second["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["id"] == "bad")
        .unwrap();
    assert_eq!(bad["session_id"], "bad-session", "{second}");
    assert_eq!(bad["attempts"], 2, "{second}");
    // The re-run continued the original branch.
    let show = Command::new("git")
        .args(["show", "grove/smn-bad:src/bad.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    assert!(show.status.success(), "{second}");

    // The resumed run's own manifest retains the original resolved backend
    // and settings, not the current file or SUMMONER_* tuning values.
    let resumed_id = second["run_id"].as_str().unwrap();
    let manifest: Value = serde_json::from_slice(
        &std::fs::read(
            fixture
                .base
                .path()
                .join("xdg/summoner/runs")
                .join(resumed_id)
                .join("manifest.json"),
        )
        .unwrap(),
    )
    .unwrap();
    assert_eq!(manifest["settings"]["max_parallel"], 2, "{manifest}");
    assert_eq!(manifest["settings"]["revise"], 0, "{manifest}");
    assert!(manifest["backends"].get("fake").is_some(), "{manifest}");
    assert!(manifest["backends"].get("poison").is_none(), "{manifest}");
    for order in manifest["orders"].as_array().unwrap() {
        assert_eq!(order["roles"]["executor"], "fake", "{manifest}");
        assert!(
            order["source_path"]
                .as_str()
                .is_some_and(|path| path.contains("resume-orders")),
            "{manifest}"
        );
    }
}

#[test]
fn resume_fails_closed_when_the_recorded_executor_binary_drifts() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);
    let first = fixture.run_report(&[&order], 0);
    let run_id = first["run_id"].as_str().unwrap();
    use std::io::Write;
    std::fs::OpenOptions::new()
        .append(true)
        .open(fixture.base.path().join("fake-executor.sh"))
        .unwrap()
        .write_all(b"\n# upgraded\n")
        .unwrap();

    let resumed = fixture.summoner(&["resume", run_id]);
    assert_eq!(resumed.status.code(), Some(2));
    let error = String::from_utf8_lossy(&resumed.stderr);
    assert!(error.contains("executor binary drift"), "{error}");
    assert!(error.contains("start a new run"), "{error}");
}

#[test]
fn hard_kill_after_grove_finish_recovers_without_report_or_source_order() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn recovered() {}' > src/recovered.rs\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order(
        "recover.toml",
        "id = \"recover\"\ntitle = \"Recover\"\nbrief = \"Survive a hard kill.\"\n\
         scope = [\"src/recovered.rs\"]\nverify_profile = \"fast\"\n",
    );

    // Hold only the first release call. This creates a deterministic kill
    // point after Grove finished and Summoner flushed its full checkpoint,
    // but before an order_finished event or report.json can exist.
    let wrapper = fixture.base.path().join("grove-release-barrier.sh");
    let blocked = fixture.base.path().join("release-blocked");
    let proceed = fixture.base.path().join("release-proceed");
    std::fs::write(
        &wrapper,
        "#!/bin/sh\n\
         if [ \"$1\" = worktree ] && [ \"$2\" = release ] && [ ! -e \"$SUMMONER_RELEASE_PROCEED\" ]; then\n\
           : > \"$SUMMONER_RELEASE_BLOCKED\"\n\
           while [ ! -e \"$SUMMONER_RELEASE_PROCEED\" ]; do sleep 0.05; done\n\
         fi\n\
         exec \"$SUMMONER_REAL_GROVE\" \"$@\"\n",
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
    let mut command =
        fixture.summoner_command(&["run", order.to_str().unwrap()], wrapper.to_str().unwrap());
    command
        .env("SUMMONER_REAL_GROVE", grove_bin())
        .env("SUMMONER_RELEASE_BLOCKED", &blocked)
        .env("SUMMONER_RELEASE_PROCEED", &proceed)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let child = command.spawn().unwrap();
    let deadline = Instant::now() + Duration::from_secs(20);
    while !blocked.exists() && Instant::now() < deadline {
        thread::sleep(Duration::from_millis(25));
    }
    assert!(
        blocked.exists(),
        "Summoner never reached the release barrier"
    );

    let runs_root = fixture.base.path().join("xdg/summoner/runs");
    let runs: Vec<PathBuf> = std::fs::read_dir(&runs_root)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .collect();
    assert_eq!(runs.len(), 1, "expected exactly one interrupted run");
    let old_run = &runs[0];
    let journal = std::fs::read_to_string(old_run.join("events.jsonl")).unwrap();
    let checkpoint: Value = journal
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .find(|event: &Value| event["event"] == "order_checkpoint")
        .expect("durable pre-release checkpoint");
    let worktree = PathBuf::from(checkpoint["report"]["worktree"].as_str().unwrap());
    assert!(!old_run.join("report.json").exists());

    unsafe {
        libc::kill(child.id() as libc::pid_t, libc::SIGKILL);
    }
    std::fs::write(&proceed, "").unwrap();
    let output = child.wait_with_output().unwrap();
    assert!(
        !output.status.success(),
        "the original run must be hard-killed"
    );
    let deadline = Instant::now() + Duration::from_secs(10);
    while worktree.exists() && Instant::now() < deadline {
        thread::sleep(Duration::from_millis(25));
    }
    assert!(
        !worktree.exists(),
        "Grove release did not complete after the kill"
    );

    // Neither mutable source orders nor current executor defaults participate
    // in recovery. The checkpoint and matching Grove receipt carry the work.
    std::fs::remove_file(&order).unwrap();
    std::fs::write(
        fixture.repo.join(".summoner.toml"),
        "default_executor = \"poison\"\n[executors.poison]\nargv = [\"false\"]\nprompt = \"stdin\"\n",
    )
    .unwrap();
    fixture.commit_all("replace current summoner config");
    let run_id = old_run.file_name().unwrap().to_str().unwrap();
    let resumed = fixture.summoner(&["resume", run_id]);
    assert_eq!(
        resumed.status.code(),
        Some(0),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&resumed.stdout),
        String::from_utf8_lossy(&resumed.stderr)
    );
    let report: Value = serde_json::from_slice(&resumed.stdout).unwrap();
    assert_eq!(report["summary"]["verified"], 1, "{report}");
    assert!(
        report["orders"][0]["detail"]
            .as_str()
            .is_some_and(|detail| detail.contains("carried from run")),
        "{report}"
    );

    // A resumed run is itself replayable even when every order was carried.
    let resumed_manifest: Value = serde_json::from_slice(
        &std::fs::read(
            runs_root
                .join(report["run_id"].as_str().unwrap())
                .join("manifest.json"),
        )
        .unwrap(),
    )
    .unwrap();
    assert_eq!(resumed_manifest["orders"].as_array().unwrap().len(), 1);
    assert_eq!(resumed_manifest["orders"][0]["expanded"]["id"], "recover");
}

#[test]
fn resume_refuses_to_duplicate_a_nonterminal_grove_task() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn held() {}' > src/held.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order(
        "held.toml",
        "id = \"held\"\ntitle = \"Held\"\nbrief = \"Hold before execution.\"\n\
         scope = [\"src/held.rs\"]\nverify_profile = \"fast\"\n",
    );
    let wrapper = fixture.base.path().join("grove-exec-barrier.sh");
    let blocked = fixture.base.path().join("exec-blocked");
    let proceed = fixture.base.path().join("exec-proceed");
    std::fs::write(
        &wrapper,
        "#!/bin/sh\n\
         if [ \"$1\" = task ] && [ \"$2\" = exec ]; then\n\
           : > \"$SUMMONER_EXEC_BLOCKED\"\n\
           while [ ! -e \"$SUMMONER_EXEC_PROCEED\" ]; do sleep 0.05; done\n\
         fi\n\
         exec \"$SUMMONER_REAL_GROVE\" \"$@\"\n",
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
    let mut command =
        fixture.summoner_command(&["run", order.to_str().unwrap()], wrapper.to_str().unwrap());
    command
        .env("SUMMONER_REAL_GROVE", grove_bin())
        .env("SUMMONER_EXEC_BLOCKED", &blocked)
        .env("SUMMONER_EXEC_PROCEED", &proceed)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let child = command.spawn().unwrap();
    let deadline = Instant::now() + Duration::from_secs(20);
    while !blocked.exists() && Instant::now() < deadline {
        thread::sleep(Duration::from_millis(25));
    }
    assert!(blocked.exists(), "Summoner never reached the exec barrier");

    let runs_root = fixture.base.path().join("xdg/summoner/runs");
    let old_run = std::fs::read_dir(&runs_root)
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path();
    let journal = std::fs::read_to_string(old_run.join("events.jsonl")).unwrap();
    let dispatched: Value = journal
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .find(|event: &Value| event["event"] == "order_dispatched")
        .expect("dispatch record");
    let task_id = dispatched["task_id"].as_str().unwrap();
    let run_id = old_run.file_name().unwrap().to_str().unwrap();
    let duplicate = fixture.summoner(&["resume", run_id]);
    assert_eq!(duplicate.status.code(), Some(2));
    let error = String::from_utf8_lossy(&duplicate.stderr);
    assert!(error.contains("still owns Grove task"), "{error}");
    assert!(error.contains(task_id), "{error}");
    let status: Value =
        serde_json::from_slice(&fixture.grove(&["task", "status", "--json"]).stdout).unwrap();
    assert_eq!(status["tasks"].as_array().unwrap().len(), 1, "{status}");

    std::fs::write(&proceed, "").unwrap();
    let original = child.wait_with_output().unwrap();
    assert_eq!(
        original.status.code(),
        Some(0),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&original.stdout),
        String::from_utf8_lossy(&original.stderr)
    );
}

#[test]
fn resume_fails_closed_when_green_journal_evidence_contradicts_grove() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn contradiction() {}' > src/contradiction.rs\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order(
        "contradiction.toml",
        "id = \"contradiction\"\ntitle = \"Contradiction\"\nbrief = \"Create work.\"\n\
         scope = [\"src/contradiction.rs\"]\nverify_profile = \"fast\"\n",
    );
    let report = fixture.run_report(&[&order], 0);
    let run_id = report["run_id"].as_str().unwrap();
    let journal_path = fixture
        .base
        .path()
        .join("xdg/summoner/runs")
        .join(run_id)
        .join("events.jsonl");
    let mut records: Vec<Value> = std::fs::read_to_string(&journal_path)
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    let terminal = records
        .iter_mut()
        .find(|record| record["event"] == "order_finished")
        .unwrap();
    terminal["report"]["finish"]["verified"] = Value::Bool(false);
    let text = records
        .iter()
        .map(serde_json::to_string)
        .collect::<Result<Vec<_>, _>>()
        .unwrap()
        .join("\n")
        + "\n";
    std::fs::write(&journal_path, text).unwrap();

    let resumed = fixture.summoner(&["resume", run_id]);
    assert_eq!(resumed.status.code(), Some(2));
    let error = String::from_utf8_lossy(&resumed.stderr);
    assert!(
        error.contains("disagrees with Grove verification"),
        "{error}"
    );
}

#[test]
fn resume_rejects_an_approval_bound_to_a_different_grove_source() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn approved() {}' > src/approved.rs\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    fixture.reviewer("echo '{\"verdict\":\"approve\",\"findings\":[]}'");
    let order = fixture.order(
        "approved.toml",
        "id = \"approved\"\ntitle = \"Approved\"\nbrief = \"Create work.\"\n\
         scope = [\"src/approved.rs\"]\nverify_profile = \"fast\"\n",
    );
    let report = fixture.run_report(&[&order], 0);
    assert_eq!(report["orders"][0]["outcome"], "approved", "{report}");
    let run_id = report["run_id"].as_str().unwrap();

    let wrapper = fixture.base.path().join("grove-wrong-source.sh");
    std::fs::write(
        &wrapper,
        r#"#!/bin/sh
if [ "$1" = task ] && [ "$2" = status ]; then
  "$SUMMONER_REAL_GROVE" "$@" > "$SUMMONER_STATUS_OUT" || exit $?
  python3 - "$SUMMONER_STATUS_OUT" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as source:
    status = json.load(source)
for task in status["tasks"]:
    task["source_sha256"] = "0" * 64
json.dump(status, sys.stdout)
PY
  exit $?
fi
exec "$SUMMONER_REAL_GROVE" "$@"
"#,
    )
    .unwrap();
    std::fs::set_permissions(&wrapper, std::fs::Permissions::from_mode(0o755)).unwrap();
    let resumed = fixture
        .summoner_command(&["resume", run_id], wrapper.to_str().unwrap())
        .env("SUMMONER_REAL_GROVE", grove_bin())
        .env(
            "SUMMONER_STATUS_OUT",
            fixture.base.path().join("status.json"),
        )
        .output()
        .unwrap();
    assert_eq!(resumed.status.code(), Some(2));
    let error = String::from_utf8_lossy(&resumed.stderr);
    assert!(error.contains("approval snapshot"), "{error}");
    assert!(
        error.contains("disagrees with Grove task source"),
        "{error}"
    );
}

#[test]
fn streamed_run_emits_ndjson_events_and_a_final_report_line() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "echo 'pub fn wave() {}' >> src/lib.rs\ngit add -A\ngit commit -qm 'executor work'",
        60,
    );
    let order = fixture.order("wave.toml", ORDER_TOML);

    let output = fixture.summoner(&["run", "--stream", order.to_str().unwrap()]);
    assert_eq!(
        output.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    // Every stdout line is one JSON object: the whole point of the stream.
    let stdout = String::from_utf8_lossy(&output.stdout);
    let lines: Vec<Value> = stdout
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).unwrap_or_else(|e| panic!("{e}: {line}")))
        .collect();
    let names: Vec<&str> = lines
        .iter()
        .map(|line| line["event"].as_str().unwrap())
        .collect();
    assert_eq!(names.first(), Some(&"run_started"), "{names:?}");
    for expected in [
        "order_started",
        "order_dispatched",
        "order_exec_done",
        "order_verify",
        "order_checkpoint",
        "order_finished",
        "run_finished",
    ] {
        assert!(names.contains(&expected), "missing {expected}: {names:?}");
    }
    assert_eq!(names.last(), Some(&"report"), "{names:?}");
    let report = &lines.last().unwrap()["report"];
    assert_eq!(report["orders"][0]["outcome"], "verified");

    // order_dispatched carries what a live consumer needs to follow along.
    let dispatched = lines
        .iter()
        .find(|line| line["event"] == "order_dispatched")
        .unwrap();
    assert!(dispatched["task_id"].is_string());
    assert!(dispatched["stdout_log"].is_string());

    // The sidecar log always exists, stream or not, and ends with run_finished.
    let run_dir = lines[0]["run_dir"].as_str().unwrap();
    let sidecar = std::fs::read_to_string(Path::new(run_dir).join("events.jsonl")).unwrap();
    let sidecar_names: Vec<String> = sidecar
        .lines()
        .map(|line| serde_json::from_str::<Value>(line).unwrap()["event"].to_string())
        .collect();
    assert_eq!(sidecar_names.last().unwrap(), "\"run_finished\"");
    assert!(!sidecar.contains("\"event\":\"report\""));
}

#[test]
fn branch_switching_executor_downgrades_success_to_error() {
    require_grove!();
    let fixture = Fixture::new(true);
    // In-scope work, receipts green — but the checkout leaves its leased
    // branch, so grove refuses the release. That worktree is leaked, and the
    // run must not call it a success.
    fixture.executor(
        "git checkout -qb rogue\necho 'pub fn r() {}' > src/rogue.rs\n\
         git add -A\ngit commit -qm rogue",
        60,
    );
    let order = fixture.order(
        "rogue.toml",
        r#"
id = "rogue"
title = "Wanders off its branch"
brief = "Commit in scope but on a different branch."
scope = ["src"]
verify_profile = "fast"
"#,
    );

    let report = fixture.run_report(&[&order], 1);
    let entry = &report["orders"][0];
    assert_eq!(entry["outcome"], "error", "{report}");
    assert!(
        entry["release_error"]
            .as_str()
            .is_some_and(|e| e.contains("manual recovery")),
        "{report}"
    );
    let worktree = entry["worktree"].as_str().unwrap();
    assert!(
        Path::new(worktree).exists(),
        "leaked worktree still on disk"
    );
}

#[test]
fn dependent_order_builds_on_its_dependency_branch() {
    require_grove!();
    let fixture = Fixture::new(true);
    // The second order proves it saw the first order's work: it refuses to
    // proceed unless src/one.rs (committed by order one) is present.
    fixture.executor(
        "branch=$(git symbolic-ref --short HEAD)\n\
         case \"$branch\" in\n\
           *smn-one) echo 'pub fn one() {}' > src/one.rs ;;\n\
           *smn-two) test -f src/one.rs || exit 9\n\
                     echo 'pub fn two() {}' > src/two.rs ;;\n\
         esac\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let a = fixture.order(
        "a.toml",
        r#"
id = "one"
title = "Touch file one"
brief = "Write src/one.rs and commit."
scope = ["src/one.rs"]
verify_profile = "fast"
"#,
    );
    let b = fixture.order(
        "b.toml",
        r#"
id = "two"
title = "Build on file one"
brief = "Write src/two.rs next to src/one.rs and commit."
scope = ["src/two.rs"]
verify_profile = "fast"
after = ["one"]
base = "grove/smn-one"
"#,
    );

    let report = fixture.run_report(&[&a, &b], 0);
    assert_eq!(report["summary"]["verified"], 2, "{report}");
    let two = report["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["id"] == "two")
        .unwrap();
    assert_eq!(two["after"], serde_json::json!(["one"]));
    // Both files exist on order two's branch: the chain composed.
    let show = Command::new("git")
        .args(["show", "grove/smn-two:src/one.rs"])
        .current_dir(&fixture.repo)
        .output()
        .unwrap();
    assert!(show.status.success(), "src/one.rs missing on smn-two");
}

#[test]
fn dependents_of_a_failed_order_are_skipped() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "branch=$(git symbolic-ref --short HEAD)\n\
         case \"$branch\" in\n\
           *smn-one) exit 3 ;;\n\
           *) echo 'pub fn two() {}' > src/two.rs\n\
              git add -A\ngit commit -qm 'executor work' ;;\n\
         esac",
        60,
    );
    let a = fixture.order(
        "a.toml",
        r#"
id = "one"
title = "Fail"
brief = "Exit 3."
scope = ["src/one.rs"]
"#,
    );
    let b = fixture.order(
        "b.toml",
        r#"
id = "two"
title = "Never runs"
brief = "Should be skipped."
scope = ["src/two.rs"]
after = ["one"]
"#,
    );

    let report = fixture.run_report(&[&a, &b], 1);
    assert_eq!(report["summary"]["executor_failed"], 1, "{report}");
    assert_eq!(report["summary"]["skipped"], 1, "{report}");
    let two = report["orders"]
        .as_array()
        .unwrap()
        .iter()
        .find(|o| o["id"] == "two")
        .unwrap();
    assert_eq!(two["outcome"], "skipped");
    assert!(
        two["detail"]
            .as_str()
            .is_some_and(|d| d.contains("\"one\"") && d.contains("executor_failed")),
        "{report}"
    );
    // The skipped order never began a task: only one grove task exists.
    assert_eq!(fixture.task_states().len(), 1);
}

#[test]
fn two_independent_orders_run_in_one_fleet_and_both_verify() {
    require_grove!();
    let fixture = Fixture::new(true);
    // One script serves both orders: the worktree branch names the order, and
    // each order writes only its own declared file.
    fixture.executor(
        "branch=$(git symbolic-ref --short HEAD)\n\
         case \"$branch\" in\n\
           *smn-one) echo 'pub fn one() {}' > src/one.rs ;;\n\
           *smn-two) echo 'pub fn two() {}' > src/two.rs ;;\n\
         esac\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let a = fixture.order(
        "a.toml",
        r#"
id = "one"
title = "Touch file one"
brief = "Write src/one.rs and commit."
scope = ["src/one.rs"]
verify_profile = "fast"
"#,
    );
    let b = fixture.order(
        "b.toml",
        r#"
id = "two"
title = "Touch file two"
brief = "Write src/two.rs and commit."
scope = ["src/two.rs"]
verify_profile = "fast"
"#,
    );

    let report = fixture.run_report(&[&a, &b], 0);
    assert_eq!(report["summary"]["verified"], 2, "{report}");
    let states = fixture.task_states();
    assert_eq!(states.len(), 2);
    assert!(states.iter().all(|(_, status)| status == "finished"));
}

/// The dependency-aware base: an order that declares `after` must build on its
/// dependency's verified commit WITHOUT the user hand-writing a base. The
/// executor exits 9 if the dependency's file is absent, so a regression here
/// fails loudly rather than producing a plausible diff on the wrong tree.
#[test]
fn a_dependent_order_inherits_its_dependency_without_an_explicit_base() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "branch=$(git symbolic-ref --short HEAD)\n\
         case \"$branch\" in\n\
           *smn-first) echo 'pub fn first() {}' > src/first.rs ;;\n\
           *smn-second) test -f src/first.rs || exit 9\n\
                        echo 'pub fn second() {}' > src/second.rs ;;\n\
         esac\n\
         git add -A\ngit commit -qm 'executor work'",
        60,
    );
    let a = fixture.order(
        "first.toml",
        r#"
id = "first"
title = "Write first"
brief = "Write src/first.rs and commit."
scope = ["src/first.rs"]
verify_profile = "fast"
"#,
    );
    // Deliberately no `base`: summoner must derive it from `after`.
    let b = fixture.order(
        "second.toml",
        r#"
id = "second"
title = "Build on first"
brief = "Write src/second.rs next to src/first.rs and commit."
scope = ["src/second.rs"]
verify_profile = "fast"
after = ["first"]
"#,
    );

    let report = fixture.run_report(&[&a, &b], 0);
    assert_eq!(report["summary"]["verified"], 2, "{report}");
    let orders = report["orders"].as_array().unwrap();
    let first = orders.iter().find(|o| o["id"] == "first").unwrap();
    let second = orders.iter().find(|o| o["id"] == "second").unwrap();

    // The dependent branched from the dependency's exact verified commit, not
    // from its branch name and not from the repository default.
    assert_eq!(
        second["base_commit"].as_str().unwrap(),
        first["candidate_commit"].as_str().unwrap(),
        "second must start at first's verified commit: {report}"
    );
    assert!(
        second["detail"]
            .as_str()
            .unwrap_or_default()
            .contains("built on first"),
        "the inheritance must be recorded: {second}"
    );
}

/// Review-required regression: an upstream that leaves uncommitted work has no
/// immutable candidate, so it records no candidate commit and its dependent
/// refuses to start rather than building on a tree missing that work. HEAD
/// alone must never be presented as the identity of a dirty candidate.
#[test]
fn a_dirty_upstream_records_no_candidate_and_its_dependent_refuses() {
    require_grove!();
    let fixture = Fixture::new(true);
    fixture.executor(
        "branch=$(git symbolic-ref --short HEAD)\n\
         case \"$branch\" in\n\
           *smn-dirty) echo 'pub fn dirty() {}' > src/one.rs ;;\n\
           *) echo 'pub fn other() {}' > src/two.rs\n\
              git add -A\ngit commit -qm 'executor work' ;;\n\
         esac",
        60,
    );
    let a = fixture.order(
        "dirty.toml",
        r#"
id = "dirty"
title = "Leave uncommitted work"
brief = "Write src/one.rs and do not commit."
scope = ["src/one.rs"]
verify_profile = "fast"
"#,
    );
    let b = fixture.order(
        "downstream.toml",
        r#"
id = "downstream"
title = "Build on dirty"
brief = "Write src/two.rs."
scope = ["src/two.rs"]
verify_profile = "fast"
after = ["dirty"]
"#,
    );

    let report = fixture.run_report(&[&a, &b], 1);
    let orders = report["orders"].as_array().unwrap();
    let dirty = orders.iter().find(|o| o["id"] == "dirty").unwrap();
    let downstream = orders.iter().find(|o| o["id"] == "downstream").unwrap();

    assert_eq!(dirty["outcome"], "verified", "{report}");
    assert!(
        dirty["candidate_commit"].is_null(),
        "a dirty candidate must not be identified by HEAD: {dirty}"
    );
    assert!(
        dirty["detail"]
            .as_str()
            .unwrap_or_default()
            .contains("uncommitted work at finish"),
        "{dirty}"
    );

    assert_eq!(downstream["outcome"], "skipped", "{downstream}");
    assert!(
        downstream["detail"]
            .as_str()
            .unwrap_or_default()
            .contains("immutable candidate"),
        "{downstream}"
    );
    assert!(
        downstream["worktree"].is_null(),
        "never dispatched: {downstream}"
    );
}
