use serde_json::Value;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use tempfile::TempDir;

const SUMMONER: &str = env!("CARGO_BIN_EXE_summoner");
const ORDER: &str = r#"
id = "portable"
title = "Run one portable fleet lifecycle"
brief = "Append the portable function to src/lib.rs and commit it."
scope = ["src"]
acceptance = ["src/lib.rs gains the portable function", "work is committed"]
verify_profile = "fast"
"#;
const GROVE_CONFIG: &str = r#"
[verification]
required = ["fast"]

[verification.profiles.fast]
continue_on_failure = false
commands = [{ argv = ["cargo", "check", "--locked"], allow_zero_tests = true }]
"#;

struct Fixture {
    base: TempDir,
    repo: PathBuf,
    order: PathBuf,
    grove: String,
}

impl Fixture {
    fn new() -> Self {
        let grove = std::env::var("SUMMONER_TEST_GROVE").unwrap_or_else(|_| "grove".into());
        require_grove(&grove);
        let base = tempfile::tempdir().expect("create fixture root");
        let repo = base.path().join("repo with space-雪");
        std::fs::create_dir_all(repo.join("src")).expect("create source directory");
        std::fs::write(
            repo.join("Cargo.toml"),
            "[package]\nname='portable-fixture'\nversion='0.1.0'\nedition='2024'\n",
        )
        .expect("write manifest");
        std::fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"portable-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("write lockfile");
        std::fs::write(repo.join("src/lib.rs"), "").expect("write source");
        std::fs::write(repo.join(".grove.toml"), GROVE_CONFIG).expect("write Grove config");
        git(&repo, &["init", "-q"]);
        git(&repo, &["config", "user.email", "fleet@example.invalid"]);
        git(&repo, &["config", "user.name", "fleet-lifecycle"]);
        let executor = fake_executor(base.path());
        std::fs::write(
            repo.join(".summoner.toml"),
            format!(
                "default_executor = \"fake\"\n\
                 default_verify_profile = \"fast\"\n\n\
                 [executors.fake]\nargv = [{}]\nprompt = \"stdin\"\ntimeout_secs = 60\n",
                toml_string(&executor)
            ),
        )
        .expect("write Summoner config");
        git(&repo, &["add", "-A"]);
        git(&repo, &["commit", "-qm", "fixture"]);
        let order = base.path().join("portable-order.toml");
        std::fs::write(&order, ORDER).expect("write work order");
        Self {
            base,
            repo,
            order,
            grove,
        }
    }

    fn summoner(&self, args: &[&str]) -> Output {
        let mut command = Command::new(SUMMONER);
        command
            .args(args)
            .current_dir(&self.repo)
            .env("SUMMONER_GROVE_BIN", &self.grove)
            .env("GROVE_CACHE_ROOT", self.base.path().join("grove-cache"))
            .env("XDG_CONFIG_HOME", self.base.path().join("config"))
            .env("XDG_CACHE_HOME", self.base.path().join("cache"))
            .env("APPDATA", self.base.path().join("appdata"))
            .output()
            .expect("run Summoner")
    }
}

#[test]
fn exact_grove_completes_one_portable_verified_lifecycle() {
    let fixture = Fixture::new();
    let order = fixture.order.to_str().expect("UTF-8 fixture path");
    let output = fixture.summoner(&["run", order]);
    assert_success(&output);
    let report: Value = serde_json::from_slice(&output.stdout).expect("parse Summoner report");
    assert_eq!(report["summary"]["verified"], 1, "{report}");
    assert_eq!(
        report["summary"]["skipped"].as_u64().unwrap_or(0),
        0,
        "{report}"
    );
    assert_eq!(report["orders"][0]["outcome"], "verified", "{report}");
    assert_eq!(report["orders"][0]["finish"]["verified"], true, "{report}");
    let worktree = report["orders"][0]["worktree"]
        .as_str()
        .expect("report carries worktree path");
    assert!(!Path::new(worktree).exists(), "Grove released the worktree");
    let committed = Command::new("git")
        .args(["show", "grove/smn-portable:src/lib.rs"])
        .current_dir(&fixture.repo)
        .output()
        .expect("read salvaged branch");
    assert_success(&committed);
    assert!(
        String::from_utf8_lossy(&committed.stdout).contains("portable_lifecycle"),
        "executor commit was not preserved"
    );
}

fn require_grove(grove: &str) {
    let version = Command::new(grove)
        .arg("--version")
        .output()
        .expect("Grove 0.3.3 must be installed or SUMMONER_TEST_GROVE must name it");
    assert_success(&version);
    assert_eq!(
        String::from_utf8_lossy(&version.stdout).trim(),
        "grove 0.3.3",
        "fleet qualification requires exact Grove 0.3.3"
    );
    let status = Command::new(grove)
        .args(["task", "status", "--json"])
        .output()
        .expect("run Grove compatibility probe");
    assert_success(&status);
    let value: Value = serde_json::from_slice(&status.stdout).expect("parse Grove task status");
    assert_eq!(value["schema_version"], 2, "wrong Grove task schema");
}

fn git(repo: &Path, args: &[&str]) {
    let output = Command::new("git")
        .args(args)
        .current_dir(repo)
        .output()
        .expect("run git");
    assert_success(&output);
}

fn toml_string(path: &Path) -> String {
    let value = path
        .to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    format!("\"{value}\"")
}

fn assert_success(output: &Output) {
    assert!(
        output.status.success(),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[cfg(unix)]
fn fake_executor(dir: &Path) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;
    let path = dir.join("fake executor-雪");
    std::fs::write(
        &path,
        "#!/bin/sh\nset -eu\nprintf 'pub fn portable_lifecycle() {}\\n' >> src/lib.rs\ngit add -A\ngit commit -qm 'portable executor'\nprintf '%s\\n' '{\"summoner_status\":\"complete\",\"unmet\":[]}'\n",
    )
    .expect("write fake executor");
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
        .expect("make fake executor executable");
    path
}

#[cfg(windows)]
fn fake_executor(dir: &Path) -> PathBuf {
    let path = dir.join("fake executor-雪.cmd");
    std::fs::write(
        &path,
        "@echo off\r\necho pub fn portable_lifecycle() {}>> src\\lib.rs\r\ngit add -A\r\ngit commit -qm \"portable executor\"\r\necho {\"summoner_status\":\"complete\",\"unmet\":[]}\r\n",
    )
    .expect("write fake executor");
    path
}
