//! Shared fixture for setup/onboarding integration tests.
#![allow(dead_code)]

use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use tempfile::TempDir;

const SUMMONER: &str = env!("CARGO_BIN_EXE_summoner");

pub struct Fixture {
    _root: TempDir,
    pub repo: PathBuf,
    pub bin: PathBuf,
    pub config: PathBuf,
    pub log: PathBuf,
}

impl Fixture {
    pub fn new() -> Self {
        let root = TempDir::new().unwrap();
        let repo = root.path().join("repo");
        let bin = root.path().join("bin");
        let config = root.path().join("config");
        let log = root.path().join("model.log");
        std::fs::create_dir_all(&repo).unwrap();
        std::fs::create_dir_all(&bin).unwrap();
        std::fs::write(repo.join("Cargo.toml"), "[workspace]\n").unwrap();
        git(&repo, &["init", "-q"]);
        git(&repo, &["config", "user.name", "setup-test"]);
        git(&repo, &["config", "user.email", "setup@example.com"]);
        let fixture = Self {
            _root: root,
            repo,
            bin,
            config,
            log,
        };
        fixture.fake_tools();
        fixture
    }

    pub fn command(&self, args: &[&str]) -> Command {
        let mut command = Command::new(SUMMONER);
        command
            .args(args)
            .current_dir(&self.repo)
            .env("XDG_CONFIG_HOME", &self.config)
            .env("APPDATA", &self.config)
            .env("FAKE_MODEL_LOG", &self.log)
            .env("PATH", prepend(&self.bin));
        for variable in [
            "CLAUDECODE",
            "CODEX_SANDBOX",
            "SUMMONER_PROFILE",
            "SUMMONER_DEFAULT_EXECUTOR",
            "SUMMONER_DEFAULT_REVIEWER",
        ] {
            command.env_remove(variable);
        }
        command
    }

    pub fn run(&self, args: &[&str]) -> Output {
        self.command(args).output().expect("run summoner")
    }

    pub fn config_path(&self) -> PathBuf {
        self.config.join("summoner").join("config.toml")
    }

    pub fn fake_tools(&self) {
        fake(
            &self.bin,
            "grove",
            r#"if [ "$1" = "--version" ]; then echo 'grove 0.4.0'; exit 0; fi
if [ "$1" = "capabilities" ]; then echo '{"schema_version":1,"grove_version":"0.4.0","status":{"repository_schema":1,"task_status_schema":4,"task_record_schema":6},"task":{"exec_capabilities":["build","edit"],"verification_policy_pinned":true},"inspection":{"binding_schema":1,"execution_schema":1,"process_tree":"unix_process_group_best_effort","filesystem":"read_only_permissions_and_digest","output":"captured_logs_json_report","finish_source_cas":true}}'; exit 0; fi
if [ "$1" = "task" ]; then echo '{"schema_version":4,"tasks":[]}'; exit 0; fi
if [ "$1" = "plan" ]; then
  # Drain partition stdin so the caller does not see Broken pipe.
  if [ "$2" = "--partition" ]; then cat >/dev/null; fi
  echo '{"sets":[],"conflicts":[],"couplings":[],"waves":[["summoner-demo"]]}'
  exit 0
fi
if [ "$1" = "exec" ] && [ "$FAKE_GROVE_FAIL_EXEC" = "1" ]; then printf 'partial\n' > Cargo.lock; echo 'injected exec failure' >&2; exit 1; fi
if [ "$1" = "exec" ]; then printf '# generated by fake Grove\nversion = 4\n' > Cargo.lock; exit 0; fi
exit 1"#,
            r#"if "%1"=="--version" (echo grove 0.4.0& exit /b 0)
if "%1"=="capabilities" (echo {"schema_version":1,"grove_version":"0.4.0","status":{"repository_schema":1,"task_status_schema":4,"task_record_schema":6},"task":{"exec_capabilities":["build","edit"],"verification_policy_pinned":true},"inspection":{"binding_schema":1,"execution_schema":1,"process_tree":"windows_job_object","filesystem":"read_only_permissions_and_digest","output":"captured_logs_json_report","finish_source_cas":true}}& exit /b 0)
if "%1"=="task" (echo {"schema_version":4,"tasks":[]}& exit /b 0)
if "%1"=="plan" (echo {"sets":[],"conflicts":[],"couplings":[],"waves":[["summoner-demo"]]}& exit /b 0)
if "%1"=="exec" if "%FAKE_GROVE_FAIL_EXEC%"=="1" ((echo partial)>Cargo.lock& echo injected exec failure 1>&2& exit /b 1)
if "%1"=="exec" ((echo # generated by fake Grove& echo version = 4)>Cargo.lock& exit /b 0)
exit /b 1"#,
        );
        for name in ["codex", "claude", "kimi"] {
            fake(
                &self.bin,
                name,
                r#"echo "$@" >> "$FAKE_MODEL_LOG"
exit 0"#,
                r#"echo %*>>"%FAKE_MODEL_LOG%"
exit /b 0"#,
            );
        }
    }
}

pub fn success(output: Output) {
    assert!(
        output.status.success(),
        "stdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

pub fn git(repo: &Path, args: &[&str]) {
    assert!(
        Command::new("git")
            .args(args)
            .current_dir(repo)
            .status()
            .unwrap()
            .success()
    );
}

pub fn git_output(repo: &Path, args: &[&str]) -> Vec<u8> {
    let output = Command::new("git")
        .args(args)
        .current_dir(repo)
        .output()
        .unwrap();
    success(output.clone());
    output.stdout
}

fn prepend(bin: &Path) -> OsString {
    let existing = std::env::var_os("PATH").unwrap_or_default();
    std::env::join_paths(std::iter::once(bin.to_path_buf()).chain(std::env::split_paths(&existing)))
        .unwrap()
}

#[cfg(unix)]
fn fake(dir: &Path, name: &str, unix: &str, _windows: &str) {
    use std::os::unix::fs::PermissionsExt;
    let path = dir.join(name);
    std::fs::write(&path, format!("#!/bin/sh\n{unix}\n")).unwrap();
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
}

#[cfg(windows)]
fn fake(dir: &Path, name: &str, _unix: &str, windows: &str) {
    std::fs::write(
        dir.join(format!("{name}.CMD")),
        format!("@echo off\r\n{windows}\r\n"),
    )
    .unwrap();
}
