//! Shared fixture for Unix fleet integration tests.
//!
//! Each fleet_* integration crate only uses a subset of helpers; dead_code
//! warnings here are expected and not a substitute for product clippy.
#![cfg(unix)]
#![allow(dead_code)]

use serde_json::Value;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use tempfile::TempDir;

pub const SUMMONER: &str = env!("CARGO_BIN_EXE_summoner");

pub const ORDER_TOML: &str = r#"
id = "wave"
title = "Add the wave function"
brief = "Append a function to src/lib.rs and commit."
scope = ["src"]
acceptance = ["src/lib.rs gains a function", "work is committed"]
verify_profile = "fast"
"#;

pub fn grove_bin() -> String {
    std::env::var("SUMMONER_TEST_GROVE").unwrap_or_else(|_| "grove".to_string())
}

pub fn require_grove() {
    let output = Command::new(grove_bin())
        .arg("--version")
        .output()
        .expect("Grove 0.4.0 must be installed or SUMMONER_TEST_GROVE must name it");
    assert!(
        output.status.success(),
        "Grove --version failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8_lossy(&output.stdout).trim(),
        "grove 0.4.0",
        "fleet tests require the exact qualified Grove release"
    );
    let output = Command::new(grove_bin())
        .args(["task", "status", "--json"])
        .output()
        .expect("run Grove task status compatibility probe");
    assert!(output.status.success(), "Grove task status probe failed");
    let status: Value =
        serde_json::from_slice(&output.stdout).expect("Grove task status must be valid JSON");
    assert_eq!(status["schema_version"], 4, "wrong Grove task schema");
}

pub struct Fixture {
    pub base: TempDir,
    pub repo: PathBuf,
    pub with_verification: bool,
}

pub const GROVE_TOML: &str = r#"[verification]
required = ["fast"]

[verification.profiles.fast]
continue_on_failure = false
commands = [{ argv = ["true"], allow_zero_tests = true }]
"#;

impl Fixture {
    /// A committed cargo package with git identity; verification profile and
    /// summoner config are committed so they predate every scope snapshot.
    pub fn new(with_verification: bool) -> Fixture {
        let base = TempDir::new().unwrap();
        let repo = base.path().join("repo");
        std::fs::create_dir_all(repo.join("src")).unwrap();
        std::fs::write(
            repo.join("Cargo.toml"),
            "[package]\nname='p'\nversion='0.1.0'\nedition='2021'\n",
        )
        .unwrap();
        std::fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"p\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        std::fs::write(repo.join("src/lib.rs"), "").unwrap();
        if with_verification {
            std::fs::write(repo.join(".grove.toml"), GROVE_TOML).unwrap();
        }
        let fixture = Fixture {
            base,
            repo,
            with_verification,
        };
        fixture.git(&["init", "-q"]);
        fixture.git(&["config", "user.email", "t@example.com"]);
        fixture.git(&["config", "user.name", "fleet-test"]);
        fixture
    }

    pub fn git(&self, args: &[&str]) {
        let status = Command::new("git")
            .args(args)
            .current_dir(&self.repo)
            .status()
            .expect("run git");
        assert!(status.success(), "git {args:?} failed");
    }

    pub fn commit_all(&self, message: &str) {
        self.git(&["add", "-A"]);
        self.git(&["commit", "-q", "-m", message]);
    }

    /// One fake executor; the config routes the prompt on stdin, which the
    /// scripts deliberately ignore (prompt composition is unit-tested).
    pub fn executor(&self, body: &str, timeout_secs: u64) {
        self.executor_raw(
            &format!("{body}\necho '{{\"summoner_status\":\"complete\",\"unmet\":[]}}'"),
            timeout_secs,
        );
    }

    pub fn executor_raw(&self, body: &str, timeout_secs: u64) {
        let script = self.base.path().join("fake-executor.sh");
        std::fs::write(
            &script,
            format!(
                "#!/bin/sh\nif [ \"${{1-}}\" = --version ]; then echo 'fake-executor 1'; exit 0; fi\n{body}\n"
            ),
        )
        .unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
        // Only point at a default profile the repository actually declares.
        let default_profile = if self.with_verification {
            "default_verify_profile = \"fast\"\n"
        } else {
            ""
        };
        std::fs::write(
            self.repo.join(".summoner.toml"),
            format!(
                "default_executor = \"fake\"\n{default_profile}\
                 max_parallel = 2\n\n[executors.fake]\nargv = [\"{}\"]\nprompt = \"stdin\"\n\
                 timeout_secs = {timeout_secs}\n",
                script.display()
            ),
        )
        .unwrap();
        self.commit_all("fixture");
    }

    /// Extra config lines appended to `.summoner.toml`. Top-level keys must be
    /// appended via this BEFORE `executor()` writes the executor table; lines
    /// appended after land inside `[executors.fake]`, which suits per-executor
    /// keys like `usage_marker`.
    pub fn append_config(&self, lines: &str) {
        use std::io::Write;
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(self.repo.join(".summoner.toml"))
            .unwrap();
        writeln!(file, "{lines}").unwrap();
        drop(file);
        self.commit_all("config tweak");
    }

    /// A "judge" reviewer backend plus `default_reviewer` pointing at it.
    /// Must run after `executor()`, which rewrites the config file whole.
    pub fn reviewer(&self, body: &str) {
        let script = self.reviewer_script(body);
        let existing = std::fs::read_to_string(self.repo.join(".summoner.toml")).unwrap();
        std::fs::write(
            self.repo.join(".summoner.toml"),
            format!(
                "default_reviewer = \"judge\"\n{existing}\n[executors.judge]\n\
                 argv = [\"{}\"]\nprompt = \"stdin\"\ntimeout_secs = 60\n",
                script.display()
            ),
        )
        .unwrap();
        self.commit_all("reviewer fixture");
    }

    pub fn reviewer_script(&self, body: &str) -> PathBuf {
        let script = self.base.path().join("judge-executor.sh");
        std::fs::write(
            &script,
            format!(
                r#"#!/bin/sh
if [ "${{1-}}" = --version ]; then echo 'fake-reviewer 1'; exit 0; fi
prompt=$(cat)
field() {{ printf '%s' "$prompt" | sed -n "s/.*\"$1\":\"\([^\"]*\)\".*/\1/p" | tail -1; }}
legacy=$({body})
verdict=$(printf '%s' "$legacy" | sed -n 's/.*"verdict":"\([^"]*\)".*/\1/p')
findings=${{legacy#*\"findings\":}}
findings=${{findings%\}}}}
printf '{{"protocol_version":1,"review_nonce":"%s","candidate_snapshot_sha256":"%s","diff_sha256":"%s","verdict":"%s","findings":%s,"reviewer":{{"provider":"judge","model":"fake"}}}}\n' \
  "$(field review_nonce)" "$(field candidate_snapshot_sha256)" "$(field diff_sha256)" "$verdict" "$findings"
"#
            ),
        )
        .unwrap();
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
        script
    }

    pub fn order(&self, name: &str, body: &str) -> PathBuf {
        let orders = self.base.path().join("orders");
        std::fs::create_dir_all(&orders).unwrap();
        let path = orders.join(name);
        std::fs::write(&path, body).unwrap();
        path
    }

    pub fn summoner(&self, args: &[&str]) -> Output {
        self.summoner_with_env(args, &[])
    }

    pub fn summoner_with_env(&self, args: &[&str], envs: &[(&str, &str)]) -> Output {
        let mut command = self.summoner_command(args, &grove_bin());
        for (key, value) in envs {
            command.env(key, value);
        }
        command.output().expect("run summoner")
    }

    pub fn summoner_command(&self, args: &[&str], grove: &str) -> Command {
        let base = std::fs::canonicalize(self.base.path()).unwrap();
        let mut command = Command::new(SUMMONER);
        command
            .args(args)
            .current_dir(&self.repo)
            .env("SUMMONER_GROVE_BIN", grove)
            .env("GROVE_CACHE_ROOT", base.join("cache"))
            .env("XDG_CONFIG_HOME", base.join("config"))
            .env("XDG_CACHE_HOME", base.join("xdg"));
        // Hermetic against the harness running THIS test suite: profile
        // auto-detection must see only what each test opts into.
        for marker in [
            "CLAUDECODE",
            "CODEX_SANDBOX",
            "CODEX_HOME",
            "SUMMONER_PROFILE",
        ] {
            command.env_remove(marker);
        }
        command
    }

    pub fn grove(&self, args: &[&str]) -> Output {
        let base = std::fs::canonicalize(self.base.path()).unwrap();
        Command::new(grove_bin())
            .args(args)
            .current_dir(&self.repo)
            .env("GROVE_CACHE_ROOT", base.join("cache"))
            .output()
            .expect("run grove")
    }

    pub fn run_report(&self, order_paths: &[&Path], expect_exit: i32) -> Value {
        let mut args = vec!["run"];
        args.extend(order_paths.iter().map(|p| p.to_str().unwrap()));
        let output = self.summoner(&args);
        assert_eq!(
            output.status.code(),
            Some(expect_exit),
            "stdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice(&output.stdout).expect("report is JSON")
    }

    pub fn task_states(&self) -> Vec<(String, String)> {
        let output = self.grove(&["task", "status", "--json"]);
        assert!(output.status.success());
        let report: Value = serde_json::from_slice(&output.stdout).unwrap();
        report["tasks"]
            .as_array()
            .unwrap()
            .iter()
            .map(|task| {
                (
                    task["owner"].as_str().unwrap_or_default().to_string(),
                    task["status"].as_str().unwrap_or_default().to_string(),
                )
            })
            .collect()
    }
}

/// Two-crate workspace (app depends on core) under a temp root, with git identity.
pub fn two_crate_workspace() -> (TempDir, PathBuf) {
    let base = TempDir::new().unwrap();
    let repo = base.path().join("ws");
    for (name, extra) in [("core", ""), ("app", "core = { path = \"../core\" }\n")] {
        let dir = repo.join("crates").join(name);
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(
            dir.join("Cargo.toml"),
            format!(
                "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n{extra}"
            ),
        )
        .unwrap();
        std::fs::write(dir.join("src/lib.rs"), "").unwrap();
    }
    std::fs::write(
        repo.join("Cargo.toml"),
        "[workspace]\nmembers = [\"crates/core\", \"crates/app\"]\nresolver = \"2\"\n",
    )
    .unwrap();
    std::fs::write(repo.join("README.md"), "ws\n").unwrap();
    std::fs::write(repo.join(".grove.toml"), GROVE_TOML).unwrap();
    for (args, ok) in [
        (["init", "-q"].as_slice(), true),
        (&["config", "user.email", "t@example.com"], true),
        (&["config", "user.name", "fleet-test"], true),
        (&["add", "-A"], true),
        (&["commit", "-q", "-m", "init"], true),
    ] {
        let status = Command::new("git")
            .args(args)
            .current_dir(&repo)
            .status()
            .unwrap();
        assert_eq!(status.success(), ok, "git {args:?}");
    }
    (base, repo)
}

/// Shell wrapper that runs real Grove but holds the first `worktree release`
/// until `proceed` exists (after writing `blocked`).
pub fn release_barrier_wrapper(path: &Path, blocked: &Path, proceed: &Path) {
    std::fs::write(
        path,
        "#!/bin/sh\n\
         if [ \"$1\" = worktree ] && [ \"$2\" = release ] && [ ! -e \"$SUMMONER_RELEASE_PROCEED\" ]; then\n\
           : > \"$SUMMONER_RELEASE_BLOCKED\"\n\
           while [ ! -e \"$SUMMONER_RELEASE_PROCEED\" ]; do sleep 0.05; done\n\
         fi\n\
         exec \"$SUMMONER_REAL_GROVE\" \"$@\"\n",
    )
    .unwrap();
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
    let _ = (blocked, proceed); // env names documented at call sites
}

/// Wait until `path` exists or panic after `secs`.
pub fn wait_for(path: &Path, secs: u64) {
    use std::thread;
    use std::time::{Duration, Instant};
    let deadline = Instant::now() + Duration::from_secs(secs);
    while !path.exists() && Instant::now() < deadline {
        thread::sleep(Duration::from_millis(25));
    }
    assert!(path.exists(), "timed out waiting for {}", path.display());
}
